---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bongocat/public_html/
    - /bin/cp -R .github $DEPLOYPATH
    - /bin/cp -R bin $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R webroot $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp .gitattributes $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .travis.yml $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp phpunit.xml.dist $DEPLOYPATH
